services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@123
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always
  postgres-keycloak:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - lab-network
networks:
  lab-network:
    driver: bridge    
volumes:
  mssql_data:
  postgres_data: